config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
 resources :products do 
    resources :comments
  end
  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  

  
  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

  def average_rating
    comments.average(:rating).to_f
  end

# Let's add a validation to the Product model that requires all new products
# to have a name provided.
  validates :name, presence: true

  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # this is a comment
  # GET /products
  # GET /products.json
  # added some comments to see if the branch thing works

# code for entering the search field 
  def index
    #conditional to see if the search term is present 
    if params[:q]
      search_term = params[:q]
 # we can’t expect users to enter a name exactly as it is spelled 
 # in the database, for this SQL has a useful matching operator called LIKE
 # and it allows you to include a “wildcard” character (%) to indicate that 
 # the matching term may be part of a longer string. 
 # So we need to put percentage characters around our search_term string. 
 # In order for us to do this, we need to use the string substitution method 
 # that you learned in the Ruby primer, with the # character. 
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.all.order ("created_at DESC")
    @comments = @product.comments.all.paginate(:page => params[:page], :per_page => 3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # Make sure that users need to login before they can see the products page
  before_filter :authenticate_user!

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to "/static_pages/landing" }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to @products, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price, :size)
    end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comments.html.erb
<!--create the partial, which we will also display on the products show page-->

<div class="product_reviews">
  <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p> <%= comment.body %> </p>
        <p><%= "Rating: #{comment.rating}/5" %></p>
        <p>
          <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
          
          <% if signed_in? && current_user.admin? %>
            <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      
      
    </div>
  <% end %>
  <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label for="product_name">Name</label><br>
    <input id="product_name" name="product[name]" type="text" />
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add your review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
  <p>
    <%= f.label :body, "Comments" %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <div class="rating"></div>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.image_url %></td>
  <td><%= product.color %></td>
  <td><%= product.price %></td>
  <td><%= product.size %></td>
  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our Shirts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Color</th>
      <th>Price</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong></strong>
  <%= image_tag(@product.image_url, width: "350", class: "img-zoom", data_zoom_image: @product.image_url) %>
</p>

<p> 
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.price %>
</p>

<p>
  Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> 
</p>

<p>
<%= form_tag "/payments/create" do %>
  <%= render partial: "shared/stripe_checkout_button" %>
<% end %>
</p>

<!--render 'new_comment is necessary, otherwise embedding the rating function does not seem to work--> 
  <%= render 'new_comment' %>
  <%= render 'comments' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>