config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 
 resources :products do 
    resources :comments
  end
  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  

  
  root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :new, :create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NameOfApp</title>
    <!-- Embed Google Fonts --> 
    <link href='http://fonts.googleapis.com/css?family=Lora|Raleway:500|Lobster|Shadows+Into+Light|Pacifico|Amatic+SC|Lobster+Two|Special+Elite' rel='stylesheet' type='text/css'>
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js">
    </script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js">
    </script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>

<!-- Add Flash Notice Tags - the block will display a welcoming message when you are signing in --> 

    <!-- navbar starts here -->
      <nav>
        <div class="navbar navbar-inverse navbar-fixed-top" role "Navigation" id="navbar">
          <div class="container fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <div class="projectName">
                <a href="#">NoWearStore</a>
              </div>
              <!-- search functin starts here -->
              <div class="search">
              <%= form_tag("/products", method: "get") do %>
                <%= label_tag(:q, "Search for:") %>
                <%= text_field_tag(:q) %>
                <%= submit_tag("Search") %>
              <% end %>
              </div><!--Search Function ends here -->
            </div>

            <!-- end navbar-header-->
            <div class="navbar-collapse collapse">
              <ul class="navbar-collapse collapse">
                <li><%= link_to "Home", static_pages_landing_page_path %></li>
                <li><%= link_to "Products", products_path %></li>
                <li><%= link_to "About", static_pages_about_path %></li>
                <li><%= link_to "Contact", static_pages_contact_path %></li>

                <!-- add login and logout button for user -->
                <% if user_signed_in? %>
                  <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete)%>
                  </li>
                <% else %>
                  <li>
                  <%= link_to('Login', new_user_session_path)%>
                  </li>
                <% end %>
                <!-- end login section here-->
              </ul>
            </div>
          <!-- end navbar collapse -->
        </div>
        <!-- end container fluid -->

      </div>
      <!--end navbar-->
    </nav>
    <!-- Navbar ends here-->
<h1>NoWear Store</h1>

<div class=image><%= image_tag("shirt.jpg")%></div>


<h2>
  <p>Your one and only source for fancy shirts, comfy hoodies & extravagant slippers.</p>
  <p> We guarantee that all our products are made with passion.</p>
</h2>

<h3>
  <p>Including the famous "Rich Kids Of Instagram"</p>
  <p> ~ Champagne Hoodie ~ </p> 
</h3>

<a class="videolink">
<br>Also, wanna watch a fancy video?</a>
 
<%= yield %>

</body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NameOfApp</title>
    <!-- Embed Google Fonts --> 
    <link href='http://fonts.googleapis.com/css?family=Lora|Raleway:500|Lobster|Shadows+Into+Light|Pacifico|Amatic+SC|Lobster+Two|Special+Elite' rel='stylesheet' type='text/css'>
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src="//code.jquery.com/jquery-1.11.2.min.js">
    </script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js">
    </script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<!-- Add Flash Notice Tags - the block will display a welcoming message when you are signing in --> 

    <!-- navbar starts here -->
      <nav>
        <div class="navbar navbar-inverse navbar-fixed-top" role "Navigation" id="navbar">
          <div class="container fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <div class="projectName">
                <a href="#">NoWearStore</a>
              </div>
              <div class="search">
              <%= form_tag("/products", method: "get") do%>
                <%= label_tag(:q, "Search for:") %>
                <%= text_field_tag(:q) %>
                <%= submit_tag("Search") %>
              <% end %>
              </div><!--Search Function ends here -->
            </div>
            <!-- end navbar-header-->
            <div class="navbar-collapse collapse">
              <ul class="navbar-collapse collapse">
                <li><%= link_to "Home", static_pages_landing_page_path %></li>
                <li><%= link_to "Products", products_path %></li>
                <li><%= link_to "About", static_pages_about_path %></li>
                <li><%= link_to "Contact", static_pages_contact_path %></li>  <!-- add login and logout button for user -->
                <% if user_signed_in? %>
                  <li>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
                <% else %>
                  <li>
                  <%= link_to('Login', new_user_session_path) %>
                  </li>
                <% end %>
              </ul>
            </div>
          <!-- end navbar collapse -->
        </div>
        <!-- end container fluid -->

      </div>
      <!--end navbar-->
    </nav>
    <!-- Navbar ends here-->
<h1>NoWear Store</h1>

<div class=image><%= image_tag("shirt.jpg")%></div>


<h2>
  <p>Your one and only source for fancy shirts, comfy hoodies & extravagant slippers.</p>
  <p> We guarantee that all our products are made with passion.</p>
</h2>

<h3>
  <p>Including the famous "Rich Kids Of Instagram"</p>
  <p> ~ Champagne Hoodie ~ </p> 
</h3>
 
<%= yield %>

</body>
</html>